#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NPROCS=$(foamDictionary -entry numberOfSubdomains -value system/air/decomposeParDict)

runApplication blockMesh -region air
runApplication createPatch -region air -overwrite

echo "Decomposing air region"
runApplication -s decomposePar.air decomposePar -region air

echo "Running solver"
runParallel -np $NPROCS `getApplication`

echo "Reconstructing latest time"
runApplication reconstructPar -region air -latestTime

# ----------------------------------------------------------------- end-of-file
