#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NPROCS=$(foamDictionary -entry numberOfSubdomains -value system/air/decomposeParDict)

echo "Decomposing regions"
runApplication -s decomposePar.air decomposePar -region air
runApplication -s decomposePar.street decomposePar -region street
runApplication -s decomposePar.leeward decomposePar -region leeward
runApplication -s decomposePar.windward decomposePar -region windward
runApplication -s decomposePar.vegetation decomposePar -region vegetation

echo "Initializing radiation models"
runParallel -np $NPROCS faceAgglomerate -region vegetation
runParallel -np $NPROCS calcLAI -region air
runParallel -np $NPROCS viewFactorsGen -region vegetation
runParallel -np $NPROCS solarRayTracingGen -region vegetation

echo "Running solver"
runParallel -np $NPROCS `getApplication`

echo "Reconstructing latest time"
runApplication reconstructPar -allRegions -latestTime

# ----------------------------------------------------------------- end-of-file
