#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Decomposing regions"
runApplication -s decomposePar.air decomposePar -region air
runApplication -s decomposePar.buildings decomposePar -region buildings
runApplication -s decomposePar.ground decomposePar -region ground
runApplication -s decomposePar.vegetation decomposePar -region vegetation

echo "Initializing radiation models"
runParallel faceAgglomerate -region vegetation
runParallel calcLAI -region air
runParallel viewFactorsGen -region vegetation
runParallel solarRayTracingGen -region vegetation

echo "Running solver"
runParallel `getApplication`

echo "Reconstructing latest time"
runApplication reconstructPar -allRegions -latestTime

# ----------------------------------------------------------------- end-of-file
